
# cosmology
X = 0.76		 ; primordial hydrogen fraction
Y = 0.24		 ; primordial helium fraction
omega_m = 0.308 // Matter density parameter
H0  = 67.8 * 1.05e-6 // Hubble constant in Myr^-1


# quasars
NLOS = 500
z = 5.95         ; redshift of the simulation snapshot
z_qso = 5.95      ; redshift of the quasar
M1450 = -27.0
alpha = -1.7	 ;quasar spectral index lambda < 912 A
alpha2 = -0.61  ;quasar spectral index lambda > 912 A
fend =  40.0			 ; maximum source frequency in eV
NFREQ  = 80			 ; number of frequency bins
tq = 1.0  ; quasar lifetime in Myr
t_on = 1.0 ; quasar turn on time in Myr
f_duty = 0.1;   duty cycle of the quasar


# simulation 
Ncells = 2048
cellsize = 114.88970588235293 ; cellsize of the simulation sightline in *comoving kpc = 78.125/0.68
boxsize = 235294.118		; length of the simulation sightline in *comoving kpc = 160000/0.68
hubble_inv = 1.0				; 1/h. unused, kept for compatibility when cellsize and boxsize are in units of kpc/h instead of kpc
Roffset = 114.88970588235293	; in comoving kpc; if equal to cellsize it leaves out the first cell to avoid boundary effects


# IGM
background = 1.0		  ; 1.0 for uniform UV background, 0.0 for no background

